modLoader="javafml" #mandatory
loaderVersion="[31,)"
[[mods]] #mandatory
modId="starlight" #mandatory
version="1.0.0" #mandatory
displayName="Star Light Mod" #mandatory
displayURL="http://example.com/" #optional
logoFile="starlight.png" #optional
credits="Thanks to Java" #optional
authors="Eno_gamer10" #optional
description='''
A little mod who add STARS !
'''
[[dependencies.starlight]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.starlight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
